# -*- coding: utf-8 -*-
from collections import OrderedDict

import six
from pyangbind.lib.base import PybindBase
from pyangbind.lib.yangtypes import RestrictedClassType
from pyangbind.lib.yangtypes import YANGDynClass

# PY3 support of some PY2 keywords (needs improved)
if six.PY3:
    import builtins as __builtin__

    long = int
elif six.PY2:
    import __builtin__


class input_container(PybindBase):
    """
    This class was auto-generated by the PythonClass plugin for PYANG
    from YANG module node-topology - based on the path /node_topology_rpc/test/input/input-container. Each member element of
    the container is represented as a class variable - with a specific
    YANG type.
    """
    __slots__ = ('_path_helper', '_extmethods', '__argument_one', '__argument_two',)

    _yang_name = 'input-container'

    _pybind_generated_by = 'container'

    def __init__(self, *args, **kwargs):

        self._path_helper = False

        self._extmethods = False
        self.__argument_one = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="argument-one", parent=self,
                                           path_helper=self._path_helper, extmethods=self._extmethods,
                                           register_paths=False, namespace='urn:node-topology',
                                           defining_module='node-topology', yang_type='string', is_config=True)
        self.__argument_two = YANGDynClass(
            base=RestrictedClassType(base_type=int, restriction_dict={'range': ['0..255']}, int_size=8), is_leaf=True,
            yang_name="argument-two", parent=self, path_helper=self._path_helper, extmethods=self._extmethods,
            register_paths=False, namespace='urn:node-topology', defining_module='node-topology', yang_type='uint8',
            is_config=True)

        load = kwargs.pop("load", None)
        if args:
            if len(args) > 1:
                raise TypeError("cannot create a YANG container with >1 argument")
            all_attr = True
            for e in self._pyangbind_elements:
                if not hasattr(args[0], e):
                    all_attr = False
                    break
            if not all_attr:
                raise ValueError("Supplied object did not have the correct attributes")
            for e in self._pyangbind_elements:
                nobj = getattr(args[0], e)
                if nobj._changed() is False:
                    continue
                setmethod = getattr(self, "_set_%s" % e)
                if load is None:
                    setmethod(getattr(args[0], e))
                else:
                    setmethod(getattr(args[0], e), load=load)

    def _path(self):
        if hasattr(self, "_parent"):
            return self._parent._path() + [self._yang_name]
        else:
            return [u'node_topology_rpc', u'test', u'input', u'input-container']

    def _get_argument_one(self):
        """
        Getter method for argument_one, mapped from YANG variable /node_topology_rpc/test/input/input_container/argument_one (string)
        """
        return self.__argument_one

    def _set_argument_one(self, v, load=False):
        """
        Setter method for argument_one, mapped from YANG variable /node_topology_rpc/test/input/input_container/argument_one (string)
        If this variable is read-only (config: false) in the
        source YANG file, then _set_argument_one is considered as a private
        method. Backends looking to populate this variable should
        do so via calling thisObj._set_argument_one() directly.
        """
        if hasattr(v, "_utype"):
            v = v._utype(v)
        try:
            t = YANGDynClass(v, base=six.text_type, is_leaf=True, yang_name="argument-one", parent=self,
                             path_helper=self._path_helper, extmethods=self._extmethods, register_paths=False,
                             namespace='urn:node-topology', defining_module='node-topology', yang_type='string',
                             is_config=True)
        except (TypeError, ValueError):
            raise ValueError({
                'error-string': """argument_one must be of a type compatible with string""",
                'defined-type': "string",
                'generated-type': """YANGDynClass(base=six.text_type, is_leaf=True, yang_name="argument-one", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=False, namespace='urn:node-topology', defining_module='node-topology', yang_type='string', is_config=True)""",
            })

        self.__argument_one = t
        if hasattr(self, '_set'):
            self._set()

    def _unset_argument_one(self):
        self.__argument_one = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="argument-one", parent=self,
                                           path_helper=self._path_helper, extmethods=self._extmethods,
                                           register_paths=False, namespace='urn:node-topology',
                                           defining_module='node-topology', yang_type='string', is_config=True)

    def _get_argument_two(self):
        """
        Getter method for argument_two, mapped from YANG variable /node_topology_rpc/test/input/input_container/argument_two (uint8)
        """
        return self.__argument_two

    def _set_argument_two(self, v, load=False):
        """
        Setter method for argument_two, mapped from YANG variable /node_topology_rpc/test/input/input_container/argument_two (uint8)
        If this variable is read-only (config: false) in the
        source YANG file, then _set_argument_two is considered as a private
        method. Backends looking to populate this variable should
        do so via calling thisObj._set_argument_two() directly.
        """
        if hasattr(v, "_utype"):
            v = v._utype(v)
        try:
            t = YANGDynClass(v, base=RestrictedClassType(base_type=int, restriction_dict={'range': ['0..255']},
                                                         int_size=8), is_leaf=True, yang_name="argument-two",
                             parent=self, path_helper=self._path_helper, extmethods=self._extmethods,
                             register_paths=False, namespace='urn:node-topology', defining_module='node-topology',
                             yang_type='uint8', is_config=True)
        except (TypeError, ValueError):
            raise ValueError({
                'error-string': """argument_two must be of a type compatible with uint8""",
                'defined-type': "uint8",
                'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=int, restriction_dict={'range': ['0..255']}, int_size=8), is_leaf=True, yang_name="argument-two", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=False, namespace='urn:node-topology', defining_module='node-topology', yang_type='uint8', is_config=True)""",
            })

        self.__argument_two = t
        if hasattr(self, '_set'):
            self._set()

    def _unset_argument_two(self):
        self.__argument_two = YANGDynClass(
            base=RestrictedClassType(base_type=int, restriction_dict={'range': ['0..255']}, int_size=8), is_leaf=True,
            yang_name="argument-two", parent=self, path_helper=self._path_helper, extmethods=self._extmethods,
            register_paths=False, namespace='urn:node-topology', defining_module='node-topology', yang_type='uint8',
            is_config=True)

    argument_one = __builtin__.property(_get_argument_one, _set_argument_one)
    argument_two = __builtin__.property(_get_argument_two, _set_argument_two)

    _pyangbind_elements = OrderedDict([('argument_one', argument_one), ('argument_two', argument_two), ])
