# -*- coding: utf-8 -*-
from collections import OrderedDict

import six
from pyangbind.lib.base import PybindBase
from pyangbind.lib.yangtypes import YANGDynClass
from pyangbind.lib.yangtypes import YANGListType

# PY3 support of some PY2 keywords (needs improved)
if six.PY3:
    import builtins as __builtin__

    long = int
elif six.PY2:
    import __builtin__

from . import port


class node(PybindBase):
    """
    This class was auto-generated by the PythonClass plugin for PYANG
    from YANG module node-topology - based on the path /node. Each member element of
    the container is represented as a class variable - with a specific
    YANG type.
    """
    __slots__ = ('_path_helper', '_extmethods', '__node_id', '__port',)

    _yang_name = 'node'

    _pybind_generated_by = 'container'

    def __init__(self, *args, **kwargs):

        self._path_helper = False

        self._extmethods = False
        self.__node_id = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="node-id", parent=self,
                                      path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True,
                                      namespace='urn:node-topology', defining_module='node-topology',
                                      yang_type='string', is_config=True)
        self.__port = YANGDynClass(
            base=YANGListType("port_id", port.port, yang_name="port", parent=self, is_container='list',
                              user_ordered=False, path_helper=self._path_helper, yang_keys='port-id', extensions=None),
            is_container='list', yang_name="port", parent=self, path_helper=self._path_helper,
            extmethods=self._extmethods, register_paths=True, extensions=None, namespace='urn:node-topology',
            defining_module='node-topology', yang_type='list', is_config=True)

        load = kwargs.pop("load", None)
        if args:
            if len(args) > 1:
                raise TypeError("cannot create a YANG container with >1 argument")
            all_attr = True
            for e in self._pyangbind_elements:
                if not hasattr(args[0], e):
                    all_attr = False
                    break
            if not all_attr:
                raise ValueError("Supplied object did not have the correct attributes")
            for e in self._pyangbind_elements:
                nobj = getattr(args[0], e)
                if nobj._changed() is False:
                    continue
                setmethod = getattr(self, "_set_%s" % e)
                if load is None:
                    setmethod(getattr(args[0], e))
                else:
                    setmethod(getattr(args[0], e), load=load)

    def _path(self):
        if hasattr(self, "_parent"):
            return self._parent._path() + [self._yang_name]
        else:
            return [u'node']

    def _get_node_id(self):
        """
        Getter method for node_id, mapped from YANG variable /node/node_id (string)
        """
        return self.__node_id

    def _set_node_id(self, v, load=False):
        """
        Setter method for node_id, mapped from YANG variable /node/node_id (string)
        If this variable is read-only (config: false) in the
        source YANG file, then _set_node_id is considered as a private
        method. Backends looking to populate this variable should
        do so via calling thisObj._set_node_id() directly.
        """
        if hasattr(v, "_utype"):
            v = v._utype(v)
        try:
            t = YANGDynClass(v, base=six.text_type, is_leaf=True, yang_name="node-id", parent=self,
                             path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True,
                             namespace='urn:node-topology', defining_module='node-topology', yang_type='string',
                             is_config=True)
        except (TypeError, ValueError):
            raise ValueError({
                'error-string': """node_id must be of a type compatible with string""",
                'defined-type': "string",
                'generated-type': """YANGDynClass(base=six.text_type, is_leaf=True, yang_name="node-id", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:node-topology', defining_module='node-topology', yang_type='string', is_config=True)""",
            })

        self.__node_id = t
        if hasattr(self, '_set'):
            self._set()

    def _unset_node_id(self):
        self.__node_id = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="node-id", parent=self,
                                      path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True,
                                      namespace='urn:node-topology', defining_module='node-topology',
                                      yang_type='string', is_config=True)

    def _get_port(self):
        """
        Getter method for port, mapped from YANG variable /node/port (list)
        """
        return self.__port

    def _set_port(self, v, load=False):
        """
        Setter method for port, mapped from YANG variable /node/port (list)
        If this variable is read-only (config: false) in the
        source YANG file, then _set_port is considered as a private
        method. Backends looking to populate this variable should
        do so via calling thisObj._set_port() directly.
        """
        if hasattr(v, "_utype"):
            v = v._utype(v)
        try:
            t = YANGDynClass(v,
                             base=YANGListType("port_id", port.port, yang_name="port", parent=self, is_container='list',
                                               user_ordered=False, path_helper=self._path_helper, yang_keys='port-id',
                                               extensions=None), is_container='list', yang_name="port", parent=self,
                             path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True,
                             extensions=None, namespace='urn:node-topology', defining_module='node-topology',
                             yang_type='list', is_config=True)
        except (TypeError, ValueError):
            raise ValueError({
                'error-string': """port must be of a type compatible with list""",
                'defined-type': "list",
                'generated-type': """YANGDynClass(base=YANGListType("port_id",port.port, yang_name="port", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='port-id', extensions=None), is_container='list', yang_name="port", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='urn:node-topology', defining_module='node-topology', yang_type='list', is_config=True)""",
            })

        self.__port = t
        if hasattr(self, '_set'):
            self._set()

    def _unset_port(self):
        self.__port = YANGDynClass(
            base=YANGListType("port_id", port.port, yang_name="port", parent=self, is_container='list',
                              user_ordered=False, path_helper=self._path_helper, yang_keys='port-id', extensions=None),
            is_container='list', yang_name="port", parent=self, path_helper=self._path_helper,
            extmethods=self._extmethods, register_paths=True, extensions=None, namespace='urn:node-topology',
            defining_module='node-topology', yang_type='list', is_config=True)

    node_id = __builtin__.property(_get_node_id, _set_node_id)
    port = __builtin__.property(_get_port, _set_port)

    _pyangbind_elements = OrderedDict([('node_id', node_id), ('port', port), ])
