# -*- coding: utf-8 -*-
from collections import OrderedDict

import six
from pyangbind.lib.base import PybindBase
from pyangbind.lib.yangtypes import YANGDynClass

# PY3 support of some PY2 keywords (needs improved)
if six.PY3:
    import builtins as __builtin__

    long = int
elif six.PY2:
    import __builtin__


class supported_modulation_format(PybindBase):
    """
    This class was auto-generated by the PythonClass plugin for PYANG
    from YANG module node-topology - based on the path /node/port/available-transceiver/supported-modulation-format. Each member element of
    the container is represented as a class variable - with a specific
    YANG type.
    """
    __slots__ = ('_path_helper', '_extmethods', '__modulation_id', '__mod_type',)

    _yang_name = 'supported-modulation-format'

    _pybind_generated_by = 'container'

    def __init__(self, *args, **kwargs):

        self._path_helper = False

        self._extmethods = False
        self.__mod_type = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="mod-type", parent=self,
                                       path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True,
                                       namespace='urn:node-topology', defining_module='node-topology',
                                       yang_type='string', is_config=True)
        self.__modulation_id = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="modulation-id", parent=self,
                                            path_helper=self._path_helper, extmethods=self._extmethods,
                                            register_paths=True, namespace='urn:node-topology',
                                            defining_module='node-topology', yang_type='string', is_config=True)

        load = kwargs.pop("load", None)
        if args:
            if len(args) > 1:
                raise TypeError("cannot create a YANG container with >1 argument")
            all_attr = True
            for e in self._pyangbind_elements:
                if not hasattr(args[0], e):
                    all_attr = False
                    break
            if not all_attr:
                raise ValueError("Supplied object did not have the correct attributes")
            for e in self._pyangbind_elements:
                nobj = getattr(args[0], e)
                if nobj._changed() is False:
                    continue
                setmethod = getattr(self, "_set_%s" % e)
                if load is None:
                    setmethod(getattr(args[0], e))
                else:
                    setmethod(getattr(args[0], e), load=load)

    def _path(self):
        if hasattr(self, "_parent"):
            return self._parent._path() + [self._yang_name]
        else:
            return [u'node', u'port', u'available-transceiver', u'supported-modulation-format']

    def _get_modulation_id(self):
        """
        Getter method for modulation_id, mapped from YANG variable /node/port/available_transceiver/supported_modulation_format/modulation_id (string)
        """
        return self.__modulation_id

    def _set_modulation_id(self, v, load=False):
        """
        Setter method for modulation_id, mapped from YANG variable /node/port/available_transceiver/supported_modulation_format/modulation_id (string)
        If this variable is read-only (config: false) in the
        source YANG file, then _set_modulation_id is considered as a private
        method. Backends looking to populate this variable should
        do so via calling thisObj._set_modulation_id() directly.
        """
        if hasattr(v, "_utype"):
            v = v._utype(v)
        try:
            t = YANGDynClass(v, base=six.text_type, is_leaf=True, yang_name="modulation-id", parent=self,
                             path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True,
                             namespace='urn:node-topology', defining_module='node-topology', yang_type='string',
                             is_config=True)
        except (TypeError, ValueError):
            raise ValueError({
                'error-string': """modulation_id must be of a type compatible with string""",
                'defined-type': "string",
                'generated-type': """YANGDynClass(base=six.text_type, is_leaf=True, yang_name="modulation-id", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:node-topology', defining_module='node-topology', yang_type='string', is_config=True)""",
            })

        self.__modulation_id = t
        if hasattr(self, '_set'):
            self._set()

    def _unset_modulation_id(self):
        self.__modulation_id = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="modulation-id", parent=self,
                                            path_helper=self._path_helper, extmethods=self._extmethods,
                                            register_paths=True, namespace='urn:node-topology',
                                            defining_module='node-topology', yang_type='string', is_config=True)

    def _get_mod_type(self):
        """
        Getter method for mod_type, mapped from YANG variable /node/port/available_transceiver/supported_modulation_format/mod_type (string)
        """
        return self.__mod_type

    def _set_mod_type(self, v, load=False):
        """
        Setter method for mod_type, mapped from YANG variable /node/port/available_transceiver/supported_modulation_format/mod_type (string)
        If this variable is read-only (config: false) in the
        source YANG file, then _set_mod_type is considered as a private
        method. Backends looking to populate this variable should
        do so via calling thisObj._set_mod_type() directly.
        """
        if hasattr(v, "_utype"):
            v = v._utype(v)
        try:
            t = YANGDynClass(v, base=six.text_type, is_leaf=True, yang_name="mod-type", parent=self,
                             path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True,
                             namespace='urn:node-topology', defining_module='node-topology', yang_type='string',
                             is_config=True)
        except (TypeError, ValueError):
            raise ValueError({
                'error-string': """mod_type must be of a type compatible with string""",
                'defined-type': "string",
                'generated-type': """YANGDynClass(base=six.text_type, is_leaf=True, yang_name="mod-type", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:node-topology', defining_module='node-topology', yang_type='string', is_config=True)""",
            })

        self.__mod_type = t
        if hasattr(self, '_set'):
            self._set()

    def _unset_mod_type(self):
        self.__mod_type = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="mod-type", parent=self,
                                       path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True,
                                       namespace='urn:node-topology', defining_module='node-topology',
                                       yang_type='string', is_config=True)

    modulation_id = __builtin__.property(_get_modulation_id, _set_modulation_id)
    mod_type = __builtin__.property(_get_mod_type, _set_mod_type)

    _pyangbind_elements = OrderedDict([('modulation_id', modulation_id), ('mod_type', mod_type), ])
