# -*- coding: utf-8 -*-
from collections import OrderedDict

import six
from pyangbind.lib.base import PybindBase
from pyangbind.lib.yangtypes import YANGDynClass

# PY3 support of some PY2 keywords (needs improved)
if six.PY3:
    import builtins as __builtin__

    long = int
elif six.PY2:
    import __builtin__


class elements(PybindBase):
    """
    This class was auto-generated by the PythonClass plugin for PYANG
    from YANG module node-topology - based on the path /node_topology_rpc/test/output/elements. Each member element of
    the container is represented as a class variable - with a specific
    YANG type.
    """
    __slots__ = ('_path_helper', '_extmethods', '__response_value',)

    _yang_name = 'elements'

    _pybind_generated_by = 'container'

    def __init__(self, *args, **kwargs):

        self._path_helper = False

        self._extmethods = False
        self.__response_value = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="response-value", parent=self,
                                             path_helper=self._path_helper, extmethods=self._extmethods,
                                             register_paths=False, namespace='urn:node-topology',
                                             defining_module='node-topology', yang_type='string', is_config=True)

        load = kwargs.pop("load", None)
        if args:
            if len(args) > 1:
                raise TypeError("cannot create a YANG container with >1 argument")
            all_attr = True
            for e in self._pyangbind_elements:
                if not hasattr(args[0], e):
                    all_attr = False
                    break
            if not all_attr:
                raise ValueError("Supplied object did not have the correct attributes")
            for e in self._pyangbind_elements:
                nobj = getattr(args[0], e)
                if nobj._changed() is False:
                    continue
                setmethod = getattr(self, "_set_%s" % e)
                if load is None:
                    setmethod(getattr(args[0], e))
                else:
                    setmethod(getattr(args[0], e), load=load)

    def _path(self):
        if hasattr(self, "_parent"):
            return self._parent._path() + [self._yang_name]
        else:
            return [u'node_topology_rpc', u'test', u'output', u'elements']

    def _get_response_value(self):
        """
        Getter method for response_value, mapped from YANG variable /node_topology_rpc/test/output/elements/response_value (string)
        """
        return self.__response_value

    def _set_response_value(self, v, load=False):
        """
        Setter method for response_value, mapped from YANG variable /node_topology_rpc/test/output/elements/response_value (string)
        If this variable is read-only (config: false) in the
        source YANG file, then _set_response_value is considered as a private
        method. Backends looking to populate this variable should
        do so via calling thisObj._set_response_value() directly.
        """
        if hasattr(v, "_utype"):
            v = v._utype(v)
        try:
            t = YANGDynClass(v, base=six.text_type, is_leaf=True, yang_name="response-value", parent=self,
                             path_helper=self._path_helper, extmethods=self._extmethods, register_paths=False,
                             namespace='urn:node-topology', defining_module='node-topology', yang_type='string',
                             is_config=True)
        except (TypeError, ValueError):
            raise ValueError({
                'error-string': """response_value must be of a type compatible with string""",
                'defined-type': "string",
                'generated-type': """YANGDynClass(base=six.text_type, is_leaf=True, yang_name="response-value", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=False, namespace='urn:node-topology', defining_module='node-topology', yang_type='string', is_config=True)""",
            })

        self.__response_value = t
        if hasattr(self, '_set'):
            self._set()

    def _unset_response_value(self):
        self.__response_value = YANGDynClass(base=six.text_type, is_leaf=True, yang_name="response-value", parent=self,
                                             path_helper=self._path_helper, extmethods=self._extmethods,
                                             register_paths=False, namespace='urn:node-topology',
                                             defining_module='node-topology', yang_type='string', is_config=True)

    response_value = __builtin__.property(_get_response_value, _set_response_value)

    _pyangbind_elements = OrderedDict([('response_value', response_value), ])
